apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-serviceaccount-pod
  name: sample-serviceaccount-pod
  namespace: default
spec:
  serviceAccountName: sample-serviceaccount 
  automountServiceAccountToken: true
  containers:
  - image: nginx:1.18.0-alpine
    name: sample-serviceaccount-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
