apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-noroot
  name: sample-noroot
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: nginx:1.16
    name: sample-noroot
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
