apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-readonly
  name: sample-readonly
spec:
  containers:
  - image: alpine
    name: sample-readonly
    args: 
    - sleep
    - "3600"
    securityContext:
      readOnlyRootFilesystem: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
