apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-runuser
  name: sample-runuser
spec:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    supplementalGroups:
    - 1001
    - 1002
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine
    name: sample-runuser
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
