apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-privilegd
  name: sample-privilegd
spec:
  containers:
  - image: nginx:1.16
    name: sample-privilegd
    securityContext:
      privileged: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
